module.exports = [
    `So much gay that the rainbow gets jealous.`,
    `Yes, but it's okay to be gay.`,
    `So gay it's not safe to sleep on the same room.`,
    `Ha, GAY!!!`,
    `https://youtu.be/YaG5SAw1n0c`,
    `Gay? He can't even get a cold, imagine a man.`,
    `( ͡° ͜ʖ ͡°)`,
    `You can't get her pregnant if she's a he.`,
    `gay af`,
    `So gay I bet he farts rainbows.`,
    `Even his boyfriend thinks he's gay.`,
    `I mean, some people like ass, some like it in the ass.`,
    `Turbo gay.`,
    `What are you fucking gay?`,
    `Anyone is gay for Justin Bieber.`,
    `( ͡° ͜ʖ ͡°) WOULDN'T YOU LIKE TO KNOW ( ͡° ͜ʖ ͡°)`,
    `Alright the test results came in today, sorry to tell the bad news but, you're a faggot.`,
    `Now look at this faggot, that I just found.`,
    `It depends, did he watch spongebob when he was a kid?`,
    `It depends, if his ring finger and index finger are the same size, he is confirmed gay.`,
    `I'm sorry, but he's not available.`,
    `Sorry to say that but he's not into you.`,
    `Yes, and he's taken, stay away from him.`,
    `Not only that but he's also single!`,
    `Of course not! He has a boyfriend.`,
    `Just be careful to not drop the soap when you're showering with him.`
];
