module.exports = [
    "Ask me something, idiot.",
    "Ask me something you moron.",
    "Try asking something, dumbass.",
    "Hey dummy! Try asking me something!",
    "Yes, yes I do work, now try asking me something.",
    "You called?",
    "Hewwo?",
    "Yes?",
    "uwu",
    "What do you want?",
    "Can't you see I'm busy?",
    "Oh hi Mark.",
    "Yes, thats how you call me, now make a fucking question.",
    "What the fuck do you want from me?",
    "Hello, I am 8ball, the Bot sent by CyberLife.",
    "Yes, I am here, I was created to be here, now if you can just move on and ask me something instead of waiting to see my response. That'd be great.",
    "Just saying, but if you typed \"8ball\", what disability kept you from typing further?",
    "Have you tried making a question? I think you'll love it!",
    "Type \"8ball help\" for help, if you just wanted me to be here for you, you could use some friends.",
    "I was not created for company, get yourself a Waifu Bot.",
    "Never fear, 8 Bot is here!",
    "Roses are red, Violets are blue, You didn't ask me anything, So I shall not answer you."
]
