module.exports = [
    "Without a doubt.",
    "It is certain.",
    "It is decidedly so.",
    "Yes, definitely.",
    "You may rely on it.",
    "As I see it, yes.",
    "Most likely.",
    "Outlook good.",
    "Signs point to yes.",
    "Ask again later.",
    "Reply hazy try again.",
    "Try again later.",
    "Better not tell you now.",
    "Cannot predict now.",
    "Concentrate and ask again.",
    "Don't count on it.",
    "My reply is no.",
    "My sources say no.",
    "Outlook not so good.",
    "Very doubtful.",
    "Yes.",
    "No.",
    "Yep.",
    "Nope.",
    "y35.",
    "n0.",
    "Only the prophecy will tell.",
    "Who cares? We all die in the end.",
    "Isn't it obvious?",
    "Obviously, yes.",
    "Yes, duh?",
    "I don't think so, no.",
    "Who gives a fuck?",
    "You wish.",
    "Is this a joke?",
    "Ask me if I care.",
    "Fuck do I know, I'm just a magic ball.",
    "No God, please, no.",
    "Just google it.",
    "Bitch, I don't know your life.",
    "Google might have the answer.",
    "Help! I'm trapped!",
    "Perhaps.",
    "Maybe, just maybe.",
    "You bet!",
    "Grow up and make your own decisions, idiot.",
    "Trust me, you don't want to know.",
    "No Ron.",
    "Ask Michael.",
    "Hell if I know.",
    "Barely possible.",
    "It's a secret to everybody.",
    "It depends.",
    "Don't take my word for it.",
    "Yeah, right.",
    "Sure, if you think so.",
    "In your dreams.",
    "Sounds good to me.",
    "Not yet.",
    "Probably.",
    "Very likely.",
    "Very unlikely.",
    "Not advisable.",
    "Give it time.",
    "When the planets align.",
    "You already know the answer to that.",
    "Maybe, in a few weeks, if you're lucky.",
    "Never in a million years, maybe in fewer.",
    "It smells like it.",
    "Possibly, but possibly it is impossible.",
    "They didn't allow me to tell you.",
    "No fucking way.",
    "Oh hell no!",
    "Kill them, kill all of them.",
    "Anything is possible.",
    "In theory, yes.",
    "I don't even know what to answer you.",
    "I don't know and I don't care.",
    "The answer is C.",
    "Ask me again tomorrow.",
    "I strongly believe so.",
    "It looks like it.",
    "I wouldn't worry about it."
];
