module.exports = [
    `0`,
    `1`,
    `We are number one!`,
    `Huan`,
    `You rolled a 2`,
    `2²/2`,
    `Too`,
    `That one title that will never be a trilogy`,
    `2+2 is 4 minus 1 that's 3 quick maths`,
    `Tree`,
    `2+2`,
    `4`,
    `Four`,
    `5`,
    `numbuh 5`,
    `Tea Time`,
    `3²-3`,
    `6`,
    `sex, wait no-`,
    `7eleven`,
    `The 4th prime number`,
    `The Lucky Number`,
    `M8`,
    `8`,
    `My number`,
    `NEIN NEIN NEIN`,
    `Numbuh 9`,
    `9 or so`,
    `Top 10 Idiots who have USED this feature`,
    `That's a ten!`,
    `10`,
    `11seven`,
    `11`,
    `11`,
    `High Noon`,
    `12 o'clock`,
    `12`,
    `13 reasons why`,
    `The Unlucky Number`,
    `13`,
    `7 but twice`,
    `14`,
    `14 Again`,
    `Number 15: Burger King Foot Lettuce`,
    `15`,
    `Three quarters of 20`,
    `Sexteen, wait no`,
    `16`,
    `Sex-teen, wait hold up`,
    `17`,
    `17`,
    `17`,
    `118-10²`,
    `18`,
    `You're now legal in most countries.`,
    `9+10`,
    `19`,
    `Almost a Nat 20`,
    `Critical 20`,
    `Nat 20`,
    `20!`
];
