module.exports = [
    `Don't ask "why?", ask "why not?"`,
    `Because logic.`,
    `Because thats good game design, of course.`,
    `Because I said so.`,
    `Because when a mommy bee and a daddy bee love themselves very very much...`,
    `You ask too many questions.`,
    `BECAUSE SCIENCE, BITCH`,
    `Are you defying my absolute logic?`,
    `Because luck is on your side, I guess.`,
    `Because a Magical 8-Ball told you so.`,
    `Because money, money is always a good reason.`,
    `why are you asking me? I don't give explanations lmao '-'`,
    `Because you're asking an 8-ball for reasoning, and for today's standards that is stupid enough.`,
    `Because I'm ordering you.`,
    `Because you can make a religion out of it.`,
    `Because 100 years from now, nobody will give a shit.`,
    `Because you can't do worse than EA.`,
    `Because you're wasting your time with me.`,
    `Because it can't go as bad as Bee Movie's plot.`,
    `Caus I'm hella c00l and if you wanna be as c00l as me you gotta start somewhere kiddo, yeah!`,
    `Because people kept fucking asking "why" to a Magic 8-Ball that is supposed to answer yes-or-no questions, that's why.`,
    `Because its possible.`,
    `Because its mathematically probable.`,
    `Because Hitler built a wall over a single night, and Trump can't even pay for one.`,
    `You're expecting too much from me.`,
    `Wait, wait, wait, you want ME, to give YOU explanations?`,
    `Because nothing will ever beat sliced bread.`,
    `I'll do you one better, WHY are you asking a "why" question to a yes-or-no Bot?`,
    `I'll do you one better, why is Gamora?`,
    `Because exceptions may apply.`,
    `Because its probably explained with religion, probably.`,
    `Because its probably explained with science, probably.`,
    `Because my word is law.`,
    `Because I can.`,
    `Because DC will never be better than Marvel.`,
    `Because journalists said so.`,
    `Because if it all goes wrong you can have the excuse that an 8-ball told you so.`,
    `Because a bird told you so.`,
    `Because freedom.`,
    `Because I don't give a fuck.`,
    `Because it can make it to the montage.`,
    `Because if it goes wrong it'll go to a cringe compilation.`
]
